#!/bin/bash

if [[ "$BRANCH" == "master" ]]; then


	cat > README.md << "EOL"

# Dockerfiles

Dockerfile repository; automatically built at [docker hub](https://hub.docker.com/u/wessm/)

For details, see specific READMEs:



EOL

	#  loop through dir
	for d in */ ; do
		name=${d%/}
		printf "* [${name}](https://github.com/wessm/Dockerfiles/tree/master/${name}/)\n\n" >> README.md
	done
	echo "README updated!"
fi




